#Project Information
site_name: Actian Data Observability
site_url: https://docs.actian.com/actian-data-observability/
site_description: >-
  Documentation for Actian Data Observability — proactively understand, detect, and resolve data quality issues.
use_directory_urls: false
docs_dir: docs
site_dir: site

# Navigation
nav:
  - Home: index.md
  - Getting Started:
    - Connect to Data:
      - Connect to Data: getting-started/connect-to-data/connect-to-data.md
      - Projects: getting-started/connect-to-data/projects.md
      - Data Connectors:
        - Data Connectors: getting-started/connect-to-data/data-connectors/data-connectors.md
        - Google BigQuery: getting-started/connect-to-data/data-connectors/google-bigquery.md
        - Google Cloud Storage: getting-started/connect-to-data/data-connectors/google-cloud-storage.md
        - Iceberg: getting-started/connect-to-data/data-connectors/iceberg.md
        - Snowflake: getting-started/connect-to-data/data-connectors/snowflake.md
        - AWS S3: getting-started/connect-to-data/data-connectors/aws-s3.md
        - AWS Athena: getting-started/connect-to-data/data-connectors/aws-athena.md
        - AWS Redshift: getting-started/connect-to-data/data-connectors/aws-redshift.md
        - Databricks Delta: getting-started/connect-to-data/data-connectors/databricks-delta.md
        - Azure Blob: getting-started/connect-to-data/data-connectors/azure-blob.md
        - Azure OneLake: getting-started/connect-to-data/data-connectors/azure-onelake.md
        - Salesforce: getting-started/connect-to-data/data-connectors/salesforce.md
        - SAP Hana: getting-started/connect-to-data/data-connectors/sap-hana.md
        - SQL Server: getting-started/connect-to-data/data-connectors/sql-server.md
        - Trino: getting-started/connect-to-data/data-connectors/trino.md
      - Supported File Types: getting-started/connect-to-data/supported-file-types.md
      - Connection Modes: getting-started/connect-to-data/connection-modes.md
      - File Path Options: getting-started/connect-to-data/file-path-options.md
      - Triggering Scans: getting-started/connect-to-data/triggering-scans.md
      - Configuring a Data Source: getting-started/connect-to-data/configuring-a-data-source.md
    - Profiling Data:
      - Profiling Data: getting-started/profiling-data/profiling-data.md
      - Data Health Metrics: getting-started/profiling-data/data-health-metrics.md
      - Data Health Overview Page: getting-started/profiling-data/data-health-overview-page.md
      - Interactive Profiling Tool - Investigator: getting-started/profiling-data/interactive-profiling-tool-investigator.md
      - Data Diff: getting-started/profiling-data/data-diff.md
      - Compound Attributes:
        - Compound Attributes: getting-started/profiling-data/compound-attributes/compound-attributes.md
        - List of Supported Functions: getting-started/profiling-data/compound-attributes/list-of-supported-functions.md
    - Monitoring Data:
      - Monitoring Data: getting-started/monitoring-data/monitoring-data.md
      - Out-of-the-Box Monitors: getting-started/monitoring-data/out-of-box-monitors.md
      - User-defined Monitors: getting-started/monitoring-data/user-defined-monitors.md
      - Built-in Metrics: getting-started/monitoring-data/built-in-metrics.md
      - User-defined Metrics: getting-started/monitoring-data/user-defined-metrics.md
      - Record Validation Rules: getting-started/monitoring-data/record-validation-rules.md
      - Rules Expression Examples: getting-started/monitoring-data/rules-expression-examples.md
      - PII Data Detection Monitors: getting-started/monitoring-data/pii-data-detection-monitors.md
      - Monitors Management: getting-started/monitoring-data/monitors-management.md
      - Creating a Monitor: getting-started/monitoring-data/creating-a-monitor.md
      - Managing Existing Monitors: getting-started/monitoring-data/managing-existing-monitors.md
      - Configuring Data-Binning: getting-started/monitoring-data/configuring-data-binning.md
      - Configuring Notifications: getting-started/monitoring-data/configuring-notifications.md
      - Monitors Troubleshooting: getting-started/monitoring-data/monitors-troubleshooting.md
      - Incident Portal: getting-started/monitoring-data/incident-portal.md
      - Data Trends and Alerts: getting-started/monitoring-data/data-trends-and-alerts.md
      - Metrics Exclusions: getting-started/monitoring-data/metrics-exclusions.md
      - Metrics Inspector: getting-started/monitoring-data/metrics-inspector.md
      - Data Quality Score: getting-started/monitoring-data/data-quality-score.md
    - Remediation:
      - Remediation: getting-started/remediation/remediation.md
      - Data Binning: getting-started/remediation/data-binning.md
      - Circuit Breaker: getting-started/remediation/circuit-breaker.md
    - Integrations:
      - Integrations: getting-started/integrations/integrations.md
      - Jira Integration: getting-started/integrations/jira-integration.md
      - Slack Integration: getting-started/integrations/slack.md
      - Jobs Status Notification: getting-started/integrations/jobs-status-notification.md
      - Data Quality External Reporting: getting-started/integrations/data-quality-external-reporting.md
      - Data Observability MCP Server: getting-started/integrations/mcp-server.md
      - Alation Integration: getting-started/integrations/alation-integration.md
    - Authentication and Access Control:
      - Authentication and Access Control: getting-started/authentication-and-access-control/auth-access-control.md
      - SSO Configuration: getting-started/authentication-and-access-control/sso-configuration.md
      - Microsoft Entra IDP Setup: getting-started/authentication-and-access-control/microsoft-entra-idp-setup.md
      - Auth0 Setup: getting-started/authentication-and-access-control/auth0-setup.md
      - Okta SSO Setup: getting-started/authentication-and-access-control/okta-sso-setup.md
      - User Management: getting-started/authentication-and-access-control/user-management.md
  - Deployment Models:
    - Deployment Models: deployment-models/deployment-models.md
    - Virtual Private Cloud (VPC) Deployment: deployment-models/virtual-private-cloud-vpc-deployment.md
  - API Reference:
    - Authentication API: api-reference/authentication-api.md
    - API Keys: api-reference/api-keys.md
    - Monitors API: api-reference/monitors-api.md
    - DQ Reporting APIs: api-reference/dq-reporting-apis.md
    - DQ Score API: api-reference/dq-score-api.md
    - Get Google Service Account API: api-reference/get-google-service-account-api.md
    - Tenant Configuration: api-reference/tenant-configuration.md
    - Actian Data Observability IP List: api-reference/telmai-ip-list.md
    - Source APIs: source-apis/list-all-sources.md
    - Upload Data:
      - Upload Data from Cloud: upload-data/upload-data-api/upload-data-from-cloud.md
      - RedShift Request Data: upload-data/upload-data-api/redshift-request-data.md
      - GCS Request Data: upload-data/upload-data-api/gcs-request-data.md
      - Azure Request Data: upload-data/upload-data-api/azure-request-data.md
      - GBQ Request Data: upload-data/upload-data-api/gbq-request-data.md
      - Snowflake Request Data: upload-data/upload-data-api/snowflake-request-data.md
      - Amazon S3 Request Data: upload-data/upload-data-api/amazon-s3-request-data.md
      - Delta Lake Request: upload-data/upload-data-api/delta-lake-request.md
      - Trino Request Data: upload-data/upload-data-api/trino-request-data.md
      - Track Upload Job: upload-data/track-job-status.md
      - Check for Alerts: upload-data/check-for-alerts.md
  - Admin APIs:
    - User Management: admin-apis/update-user.md
    - Troubleshooting: admin-apis/troubleshooting.md
  - Release Notes:
    - Release Notes: telmai-releases/release-notes/release-notes.md
    - Initial Release: telmai-releases/release-notes/initial_release.md
    - 25.1.0: telmai-releases/release-notes/25.1.0.md
    - 25.1.2: telmai-releases/release-notes/25.1.2.md
    - 25.1.3: telmai-releases/release-notes/25.1.3.md
    - 25.2.0: telmai-releases/release-notes/25.2.0.md
    - 25.2.1: telmai-releases/release-notes/25.2.1.md


# Theme Configuration
theme:
  name: material
  logo: assets/images/actian-logo.svg
  favicon: assets/favicon.png
  language: en
  custom_dir: theme_overrides/
  font: false
  palette:
    - scheme: default
      primary: custom
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.instant
    - navigation.expand
    - navigation.indexes
    - navigation.path
    - navigation.footer
    - navigation.sections
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - search.highlight
    - search.share
    - search.focus
    - search.suggest
    - toc.follow

# Markdown Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      title: On this page
      permalink: true

# Copyright
copyright: >-
  Copyright &copy; 2026, Actian

extra:
  generator: false
  homepage: https://docs.actian.com/
  social:
    - icon: fontawesome/solid/paper-plane
      link: https://www.actian.com/contact/
      name: Contact Actian Support
  tags:
    default: default

# Support
repo_url: https://www.actian.com/contact/
repo_name: Support

plugins:
  - search
  - tags
  - glightbox

# Customization
extra_css:
  - assets/stylesheets/style.css
  - stylesheets/dx_style.css
  - assets/stylesheets/actian-landing.css
  - stylesheets/comprehensive-nav.css
  - stylesheets/extra.css
  - stylesheets/toast-override.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/marked/marked.min.js
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
  - javascripts/mermaid-init.js
  - javascripts/search_enhancement.js
  - javascripts/extra.js
  - javascripts/comprehensive-nav-dataconnect.js
  - path: javascripts/current.js
    defer: true
  - javascripts/toast-fix.js
